# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: golang-github-facebook-time.spec
files_to_sync:
  - golang-github-facebook-time.spec
  - .packit.yaml

upstream_package_name: time
downstream_package_name: golang-github-facebook-time
actions:
  post-upstream-clone:
    - "bash -c \"curl -s https://src.fedoraproject.org/rpms/golang-github-facebook-time/raw/main/f/golang-github-facebook-time.spec | sed -e '/^Patch[0-9]/d' -e 's|^%global commit.*|%global commit          '$(git rev-parse HEAD)'|' -e 's|^%global date.*|%global date            '$(date +%Y%m%d)'|' -e 's|mv fbclock-bin %{gobuilddir}/bin/fbclock-bin|mkdir -p %{gobuilddir}/bin \\&\\& mv fbclock-bin %{gobuilddir}/bin/fbclock-bin|' > golang-github-facebook-time.spec\""
    - "curl -s -o go-vendor-tools.toml https://src.fedoraproject.org/rpms/golang-github-facebook-time/raw/main/f/go-vendor-tools.toml"
    - "bash -c \"curl -s https://src.fedoraproject.org/rpms/golang-github-facebook-time/raw/main/f/sources | grep vendor | sed 's/SHA512 (\\(.*\\)) = \\(.*\\)/\\1 \\2/' | while read file hash; do curl -L https://src.fedoraproject.org/repo/pkgs/rpms/golang-github-facebook-time/$file/sha512/$hash/$file -o $file && mv $file time-$(git rev-parse HEAD)-vendor.tar.bz2; done\""
  create-archive:
    - "bash -c 'git archive --prefix time-$(git rev-parse HEAD)/ --output time-$(git rev-parse HEAD).tar.gz HEAD'"
    - "bash -c 'echo time-$(git rev-parse HEAD).tar.gz'"

srpm_build_deps:
  - bash
  - curl
  - sed

jobs:
- job: copr_build
  trigger: commit
  owner: "@meta"
  project: time
  targets:
    - fedora-stable-aarch64
    - fedora-stable-ppc64le
    - fedora-stable-s390x
    - fedora-all-x86_64
- job: copr_build
  trigger: pull_request
  owner: "@meta"
  project: time
  targets:
    - fedora-stable-aarch64
    - fedora-stable-ppc64le
    - fedora-stable-s390x
    - fedora-all-x86_64
