# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: golang-github-facebook-time.spec
files_to_sync:
  - golang-github-facebook-time.spec
  - .packit.yaml

upstream_package_name: time
downstream_package_name: golang-github-facebook-time
actions:
  # Fetch the specfile from Rawhide, remove the snapshot and drop any patches
  post-upstream-clone: "bash -c \"curl -s https://src.fedoraproject.org/rpms/golang-github-facebook-time/raw/main/f/golang-github-facebook-time.spec | sed -e '/^%global commit/d' -e '/^Patch[0-9]/d' > golang-github-facebook-time.spec\""

srpm_build_deps:
  - bash
  - curl
  - sed
 
jobs:
- job: copr_build
  trigger: commit
  owner: "@meta"
  project: time
  targets:
    - fedora-all-aarch64
    # https://bugzilla.redhat.com/show_bug.cgi?id=2152259
    # - fedora-all-armhfp
    - fedora-all-ppc64le
    - fedora-all-s390x
    - fedora-all-x86_64
- job: copr_build
  trigger: pull_request
  owner: "@meta"
  project: time
  targets:
    - fedora-all-aarch64
    # https://bugzilla.redhat.com/show_bug.cgi?id=2152259
    # - fedora-all-armhfp
    - fedora-all-ppc64le
    - fedora-all-s390x
    - fedora-all-x86_64
