name: lint
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.23
      - run: sudo apt-get install libpcap-dev
      - uses: golangci/golangci-lint-action@v3
      - run: |
          go get -v -u github.com/u-root/u-root/tools/checklicenses
          go run github.com/u-root/u-root/tools/checklicenses -c .github/workflows/config.json
